apiVersion: v1
kind: Service
metadata:
  name: restapi2-data-registry-service
spec:
  type: LoadBalancer
  selector:
    app: restapi2-data-registry
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80